language: node_js
node_js:
  - '6'
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ghostscript imagemagick
  - npm install -g "gitbook-cli" "svgexport" "github:RanzQ/node-apidoc-markdown"
  - sudo -v && wget -q -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
cache:
  directories:
    - node_modules
script: |
  test $TRAVIS_PULL_REQUEST == "false" && \
  git checkout $TRAVIS_BRANCH && \
  bash scripts/build.sh
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=TAG-$TRAVIS_BRANCH
  - git push https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG :refs/tags/$GIT_TAG
  - git tag $GIT_TAG -af -m "generated tag from travis for build $TRAVIS_BUILD_NUMBER"
  - git push -qf https://$GH_TOKEN@github.com/$TRAVIS_REPO_SLUG.git --tags
deploy:
  provider: releases
  api-key: $GH_TOKEN
  file_glob: true
  file: "./*.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    tags: false
    all_branches: true
branches:
  only:
    /^book_.*$/
  except:
    /^TAG-.*$/
