language: node_js
node_js:
  - '5'
before_install:
  - npm install -g gitbook-cli
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deploy_docs.sh
env:
  global:
    secure: MriokGVLqkSQFMeQIeB75M8CLbRWs4Y0HEVPhL1szrcg0bYk/NkhTQ5+PUyVSYSKGaQwjAW+//ZAgb/r/u95mqVcGXByyvbM+CGjIYjzpGkwxPRgoFR2C41qZc7mULDy5oYv69ED9Dqdq7QGl1DGgmkR9F12KXw4OewvqWOz5qpT20iFqJZZHAK68YCsFh6ex1v42ZW4Znpteu9Ivm1lRRH3VaXztjlVxbP/7Jqpgd5r0N5bCSWmtKY4bN/TIiAanyskp+TGLrJW+zxCSGfAEby7flcZ7dsB7Ef28mjQQRomLpN/yS6hz4IZh5VUI+x898liXO2Pn/nmWAl5ts5lVOLkQZn338sBb6kfz2EY6Tq33LzOLx1WrgG/lZeb/vtcbTSHV3ISevm+El0jgfREz6sv5GTwoOmK9aIzfhDS5fWn5E7gn5SWiqKYenkVxIzghIbA2KSyfteOHDD1YeipCuSU66zyWVylWHreoPDfmHKcaneIuOK9TBeO+tWAtUmGjjdD/d0j5Gfgrvk0pF3NyMuE97vovsMKFxmEvsRkhFj7s68HcgMKHM7HbTvrBqPmCUi6u/fhQ9wchjxmQVPAso/Y9eU8rrkvUnlJaaH22I2/ftrbmWNK4cn6pQBiR3xDskK9E1ZXzJAZCKVctFXdiX3wYAqTivPEVBEJTQ/L8Pg=
