language: node_js
node_js:
  - '6'
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y ghostscript imagemagick
  - npm install -g "gitbook-cli" "svgexport" "github:RanzQ/node-apidoc-markdown"
  - sudo -v && wget -q -O- https://raw.githubusercontent.com/kovidgoyal/calibre/master/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
cache:
  directories:
    - node_modules
script: |
  test $TRAVIS_PULL_REQUEST == "false" && \
  git checkout $TRAVIS_BRANCH && \
  bash scripts/build.sh && \
  bash scripts/deploy_ghpages.sh
branches:
  only:
    /^book_.*$/
